from core.views.person_api_view import PersonListAPIView
from core.views.property_card_api_view import PropertyCardAPIView
from core.views.vehicle_api_view import VehicleAPIView, VehicleUpdateRegisterComponentsAPIView
from core.views.vehicle_engine_api_view import VehicleEngineListCreateView, VehicleEngineRetrieveUpdateDestroyView
from core.views.vehicle_accessories_api_view import VehicleAccessoriesListCreateView, VehicleAccessoriesRetrieveUpdateDestroyView
from core.views.review_api_view import ReviewListCreateView, ReviewRetrieveUpdateDestroyView
from core.views.read_property_card import ReadPropertyCardAPIView
from core.views.user_api_view import UserListCreateAPIView
from core.views.check_property_card import CheckPropertyCardAPIView