# Generated by Django 5.1.2 on 2024-10-26 03:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auto_workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('USER', 'USER'), ('AUTO_WORKSHOP', 'AUTO_WORKSHOP')], max_length=14)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNDEFINED', 'UNDEFINED')], max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('property_card_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('transit_authority', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_property_cards', to='core.person')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('type_vehicle', models.CharField(max_length=30)),
                ('doors_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('GAS', 'GAS'), ('DIESEL', 'DIESEL'), ('EXTRA', 'EXTRA')], max_length=20)),
                ('kilometric', models.PositiveIntegerField()),
                ('property_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_cards_vehicle', to='core.propertycard')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_review', to='auto_workshop.garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_review', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_cam', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('power_mirrors', models.BooleanField(default=False)),
                ('power_seats', models.BooleanField(default=False)),
                ('voice_control', models.BooleanField(default=False)),
                ('driven_assistance', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('anti_theft_system', models.BooleanField(default=False)),
                ('alarm_system', models.BooleanField(default=False)),
                ('remote_start', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_accessories', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=100)),
                ('horse_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('engine_type', models.CharField(max_length=100)),
                ('brake_system', models.CharField(max_length=100)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_engine', to='core.vehicle')),
            ],
        ),
    ]
