# Generated by Django 5.1.1 on 2024-09-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='nit',
            field=models.CharField(),
        ),
    ]
