# Generated by Django 5.1.2 on 2024-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='person', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertycard',
            name='enrollment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertycard',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertycard',
            name='transit_authority',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('DIESEL', 'DIESEL'), ('EXTRA', 'EXTRA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometric',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
