# Generated by Django 5.1.2 on 2024-12-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='initial_scan',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('UNCOMPLETED', 'UNCOMPLETED')], default='UNCOMPLETED', max_length=20),
        ),
    ]
