# Generated by Django 5.1.2 on 2024-12-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_initial_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(default='MANUAL', max_length=30),
            preserve_default=False,
        ),
    ]
