# Generated by Django 5.1.1 on 2024-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nit', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dane_code', models.CharField(max_length=150, null=True)),
                ('homologate_code', models.CharField(max_length=150, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoState',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dane_code', models.CharField(max_length=150, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('address', models.TextField()),
                ('suggested_address', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=23, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=23, null=True)),
                ('description_value', models.CharField(max_length=70, null=True)),
                ('description_number', models.CharField(max_length=70, null=True)),
                ('description_consecutive', models.CharField(max_length=70, null=True)),
                ('observation', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('code', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
