# Generated by Django 5.1.1 on 2024-10-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocity',
            name='geo_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_workshop.geostate'),
        ),
        migrations.AddField(
            model_name='location',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_location', to='auto_workshop.garage'),
        ),
        migrations.AddField(
            model_name='location',
            name='geo_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_workshop.geocity'),
        ),
        migrations.AddField(
            model_name='location',
            name='geo_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_workshop.geostate'),
        ),
        migrations.AddField(
            model_name='location',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_workshop.reference'),
        ),
    ]
